apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    componenttt: web-appp
spec:
  containers:
    - name: client
      image: amazingandyyy/react-docker
      ports:
        - containerPort: 3000